// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlypL9cVAJFmsPIGYJcbAFOVHnoLj_J_A',
    appId: '1:1021882175654:web:8a2fb770c8c94a6b1ae467',
    messagingSenderId: '1021882175654',
    projectId: 'connect-1ad01',
    authDomain: 'connect-1ad01.firebaseapp.com',
    storageBucket: 'connect-1ad01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKcTazkVQnE_NqS90bCewFAyGotCsi8ck',
    appId: '1:1021882175654:android:335829260c57bfc91ae467',
    messagingSenderId: '1021882175654',
    projectId: 'connect-1ad01',
    storageBucket: 'connect-1ad01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApZ8Gh4KfRik1vAiz4OgooikYxXuTkMGw',
    appId: '1:1021882175654:ios:2f8a79f36791b1151ae467',
    messagingSenderId: '1021882175654',
    projectId: 'connect-1ad01',
    storageBucket: 'connect-1ad01.appspot.com',
    iosBundleId: 'com.example.connectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApZ8Gh4KfRik1vAiz4OgooikYxXuTkMGw',
    appId: '1:1021882175654:ios:2f8a79f36791b1151ae467',
    messagingSenderId: '1021882175654',
    projectId: 'connect-1ad01',
    storageBucket: 'connect-1ad01.appspot.com',
    iosBundleId: 'com.example.connectapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlypL9cVAJFmsPIGYJcbAFOVHnoLj_J_A',
    appId: '1:1021882175654:web:aefc1cbf74184e681ae467',
    messagingSenderId: '1021882175654',
    projectId: 'connect-1ad01',
    authDomain: 'connect-1ad01.firebaseapp.com',
    storageBucket: 'connect-1ad01.appspot.com',
  );
}
